# Generated by Django 5.2.7 on 2025-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата меню')),
                ('salads', models.TextField(help_text='Пример: Цезарь\nОвощной', verbose_name='Салаты (каждый с новой строки)')),
                ('soups', models.TextField(verbose_name='Супы (каждый с новой строки)')),
                ('hot_dishes', models.TextField(verbose_name='Горячее (каждый с новой строки)')),
                ('garnishes', models.TextField(help_text='Пишите в свободном формате', verbose_name='Гарниры, Напитки, Десерт')),
                ('price_3_course', models.IntegerField(default=370, verbose_name='Цена: 3 блюда')),
                ('price_salad_soup', models.IntegerField(default=270, verbose_name='Цена: Салат + Суп')),
                ('price_salad_hot', models.IntegerField(default=320, verbose_name='Цена: Салат + Горячее')),
                ('price_soup_hot', models.IntegerField(default=320, verbose_name='Цена: Суп + Горячее')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бизнес-ланч',
                'verbose_name_plural': 'Бизнес-ланчи',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
    ]
