# Generated by Django 5.2.7 on 2025-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_user_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Название меню (например, 'Стандарт')")),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за человека')),
                ('cover_image', models.ImageField(upload_to='banquet_covers/', verbose_name='Обложка карточки')),
                ('layout_type', models.CharField(choices=[('image', 'Только изображение'), ('list', 'Интерактивный список')], default='list', max_length=10, verbose_name='Тип отображения')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='banquet_menus/', verbose_name="Изображение меню (если тип 'Только изображение')")),
                ('items_json', models.TextField(default='[]', help_text='Например: [{"category": "Салаты", "items": ["Оливье", "Цезарь"]}]', verbose_name='Список блюд (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Банкетное меню',
                'verbose_name_plural': 'Банкетные меню',
                'ordering': ['order'],
            },
        ),
    ]
