# Generated by Django 5.2.7 on 2025-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_banquetmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetmenu',
            name='category',
            field=models.CharField(choices=[('adult', 'Основное меню'), ('children', 'Детское меню')], default='adult', max_length=20, verbose_name='Категория меню'),
        ),
    ]
