# Generated by Django 5.2.7 on 2025-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_is_paid_order_payment_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Посетители (уник.)')),
                ('total_views', models.IntegerField(default=0, verbose_name='Просмотры страниц')),
            ],
            options={
                'verbose_name': 'Статистика посещений',
                'verbose_name_plural': 'Статистика посещений',
                'ordering': ['-date'],
            },
        ),
    ]
